version: '2.1'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links:
      - nginx
    environment:
      DOMAINS: 'fuga.kadono.work -> http://dockerhost:8081'
      STAGE: 'production'
      # WEBSOCKET: 'true'
      # FORCE_RENEW: 'true'
      # CLIENT_MAX_BODY_SIZE: 0  # これだと無制限
      # CLIENT_MAX_BODY_SIZE: 10M # とか
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal

  db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'image'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./frontend/dist:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db/image"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
      #      s3.access-key: "AKIAXDFNTWHJ3M65QKG3"
      #      s3.secret-key: "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"
      #      s3.url:
      s3.url: http://minio:9000/
    depends_on:
      - db

  ###############

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio_secret
    ports:
      - "9000:9000"
    volumes:
      - "./docker/minio/data:/data"
    command: server /data
