spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver

#####################################
#  Custom Properties
#####################################

s3:
  url: http://localhost:9000/
  access-key: minio
  secret-key: minio_secret
  timeout-mills: 5000
  region: us-east-1
  bucket-name: image
